  /*
PROJECT 1 OFFICIAL BUSINESS QUESTIONS

STORE MANAGER:
1. What is the daily revenue generated by the store?
2. How does weekday sales performance compare with weekend sales performance?
3. Which product categories are performing best?
4. Which inventory items are fast-moving?
5. What are the peak purchasing hours throughout the day?
6. What are the peak purchasing periods throughout the week?

INVENTORY PLANNER:
1. How is stock moving across stores and product categories?
2. Which products are low-performing and creating dead stock?
3. What are the seasonal sales patterns?
4. Which periods show high demand spikes such as Q4 holiday season?
5. How should procurement strategies be adjusted to avoid stockouts?
6. Which products require inventory optimization?

REGIONAL SALES DIRECTOR:
1. Which geographic locations generate the highest revenue?
2. How does revenue performance compare across multiple retail locations?
3. What is the overall financial performance of each retail node?
4. Which product categories contribute the most revenue?
5. What are the YoY and MoM growth trends across regions?
6. Which locations should receive pricing strategy adjustments?

GENERAL BUSINESS QUESTIONS:
1. What is the Total Sales generated?
2. What is the Average Revenue per Order?
3. What are the overall sales trends over a 12-month period?
4. What is the revenue contribution by product line/category?
5. What is the order volume per city?
6. What are the time-series sales trends?
7. Which months or periods contribute the highest annual revenue?
8. How can sales insights support targeted marketing strategies?
9. How can analytics improve inventory turnover?
*/